# # # # # # # # # # # # # # # # # 
#
#
#         made by TheRayZV
#       https://therayzv.ru
#
#
#

# Настройки сообщений плагина
messages:
  prefix: "&7[&crPass&7] "
  no-permission: "&cУ вас нет прав для использования этой команды!"
  player-not-found: "&cИгрок не найден!"
  pass-given: "&aПроходка выдана игроку %player% на %time%!"
  pass-given-permanent: "&aПроходка выдана игроку %player% навсегда!"
  pass-taken: "&cПроходка удалена у игрока %player%!"
  pass-extended: "&aВремя проходки продлено для игрока %player% на %time%!"
  pass-made-permanent: "&aПроходка игрока %player% сделана вечной!"
  pass-already-permanent: "&cУ игрока %player% уже есть вечная проходка!"
  pass-expired: "&cСрок вашей проходки закончился!"
  pass-info: "&aВаша проходка действует еще %time% &7(до %date%)"
  pass-info-permanent: "&aУ игрока %player% вечная проходка"
  pass-all-extended: "&aВремя проходки продлено для %count% игроков на %time%!"
  pass-all-made-permanent: "&aПроходки всех игроков (%count%) сделаны вечными!"
  pass-already-has: "&cУ игрока %player% уже есть проходка!"
  pass-not-has: "&cУ игрока %player% нет проходки!"
  unknown-command: "&cНеизвестная команда!"
  config-reloaded: "&aКонфигурация перезагружена!"
  
  # Сообщения для команды list
  pass-list-empty: "&cНа сервере нет активных проходок."
  pass-list-header: "&7------- &eСписок проходок &7-------"
  pass-list-footer: "&7Всего: &f%total% &7(&aАктивных: &f%valid%&7, &bВечных: &f%permanent%&7, &cИстекших: &f%expired%&7)"
  
  help-message: |
    &7---------- &crPass Помощь &7----------
    &e/rpass give <игрок> <время> &7- Выдать или продлить проходку
    &e/rpass take <игрок> &7- Забрать проходку
    &e/rpass extendall <время> &7- Продлить проходку всем игрокам
    &e/rpass info <игрок> &7- Информация о проходке
    &e/rpass list &7- Список всех проходок
    &e/rpass reload &7- Перезагрузить конфиг
    &e/rpass debug &7- Отладочная информация
    &7------------------------------------

# Настройки кика
kick:
  title: "&cВаша проходка истекла!"
  subtitle: "&7Обратитесь к администрации для продления"
  
  # Сообщение при попытке войти без проходки (поддерживает несколько строк)
  no-pass-message:
    - "&c&l=== У ВАС НЕТ ПРОХОДКИ! ==="
    - "&fДля получения проходки обратитесь к администрации"
    - "&fНаш Discord: &bdiscord.example.com"
    - "&fНаш сайт: &bwww.example.com"
    - "&c&l==========================="
  
  # Сообщение при кике из-за истекшей проходки (поддерживает несколько строк)
  expired-message:
    - "&c&l=== ВАША ПРОХОДКА ИСТЕКЛА! ==="
    - "&fДля продления проходки обратитесь к администрации"
    - "&fНаш Discord: &bdiscord.example.com"
    - "&fНаш сайт: &bwww.example.com"
    - "&c&l==============================="
  
  # Интервал проверки в секундах
  check-interval: 60

# Настройки плейсхолдеров
placeholders:
  # Доступные плейсхолдеры:
  # %rpass_has% - имеет ли игрок проходку (true/false)
  # %rpass_time% - время до окончания проходки с правильным склонением (например, "7 дней 12 часов 30 минут")
  # %rpass_time_compact% - компактное отображение времени (например, "7д 12ч 30м")
  # %rpass_days% - только количество дней до окончания проходки
  # %rpass_hours% - только количество часов до окончания проходки
  # %rpass_minutes% - только количество минут до окончания проходки
  # %rpass_seconds% - только количество секунд до окончания проходки
  # %rpass_permanent% - является ли проходка вечной (true/false)
  # %rpass_status% - статус проходки (Активна/Истекла/Нет проходки)
  #
  # Для использования плейсхолдеров требуется PlaceholderAPI
  # В случае ошибок, убедитесь, что:
  # 1. PlaceholderAPI установлен и активирован
  # 2. Выполнена команда /papi reload после первого запуска плагина
  # 3. Игрок имеет действующую проходку
  
  # Настройки текста для плейсхолдеров
  expired-text: "&cИстекла" # Текст для истекшей проходки
  permanent-text: "Навсегда" # Текст для вечной проходки
  no-pass-text: "Нет проходки" # Текст для отсутствующей проходки
  
  # Настройки форматирования времени для отображения в сообщениях и командах
  date-format: "dd.MM.yyyy HH:mm:ss" # Формат даты для отображения точного времени окончания проходки
  time-colors:
    normal: "&e" # Цвет обычного времени
    permanent: "&b" # Цвет вечной проходки
    expired: "&c" # Цвет истекшей проходки
    warning: "&6" # Цвет предупреждения (когда осталось мало времени) 